# coding: utf-8

"""
    Peacemakr

    This API describes the Peacemakr services, which enable seamless application layer encryption and verification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import peacemakr
from peacemakr.generated.models.crypto_config import CryptoConfig  # noqa: E501
from peacemakr.generated.rest import ApiException


class TestCryptoConfig(unittest.TestCase):
    """CryptoConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCryptoConfig(self):
        """Test CryptoConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = peacemakr.generated.models.crypto_config.CryptoConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
