# coding: utf-8

"""
    Peacemakr

    This API describes the Peacemakr services, which enable seamless application layer encryption and verification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import peacemakr
from peacemakr.generated.models.symmetric_key_use_domain import SymmetricKeyUseDomain  # noqa: E501
from peacemakr.generated.rest import ApiException


class TestSymmetricKeyUseDomain(unittest.TestCase):
    """SymmetricKeyUseDomain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSymmetricKeyUseDomain(self):
        """Test SymmetricKeyUseDomain"""
        # FIXME: construct object with mandatory attributes with example values
        # model = peacemakr.generated.models.symmetric_key_use_domain.SymmetricKeyUseDomain()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
