# coding: utf-8

"""
    Peacemakr

    This API describes the Peacemakr services, which enable seamless application layer encryption and verification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import peacemakr
from peacemakr.generated.api.phone_home_api import PhoneHomeApi  # noqa: E501
from peacemakr.generated.rest import ApiException


class TestPhoneHomeApi(unittest.TestCase):
    """PhoneHomeApi unit test stubs"""

    def setUp(self):
        self.api = peacemakr.generated.api.phone_home_api.PhoneHomeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_log_post(self):
        """Test case for log_post

        Used to report back to server a logged event  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
