# coding: utf-8

"""
    Peacemakr

    This API describes the Peacemakr services, which enable seamless application layer encryption and verification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import peacemakr_sdk
from peacemakr_sdk.models.error_response import ErrorResponse  # noqa: E501
from peacemakr_sdk.rest import ApiException


class TestErrorResponse(unittest.TestCase):
    """ErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorResponse(self):
        """Test ErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = peacemakr_sdk.models.error_response.ErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
