# coding: utf-8

"""
    Peacemakr

    This API describes the Peacemakr services, which enable seamless application layer encryption and verification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import peacemakr
from peacemakr.generated.models.key_derivation_instance import KeyDerivationInstance  # noqa: E501
from peacemakr.generated.rest import ApiException


class TestKeyDerivationInstance(unittest.TestCase):
    """KeyDerivationInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeyDerivationInstance(self):
        """Test KeyDerivationInstance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = peacemakr.generated.models.key_derivation_instance.KeyDerivationInstance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
