version: '3'
services:
  peacemakr-services:
    image: gcr.io/peacekube/peacemakr-services:latest
    depends_on:
      - redis
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - PEACEMAKR_REDIS_URL=redis:6379
  keyderiver-cloud:
    image: gcr.io/peacekube/key-derivation-service:latest
    environment:
      - PEACEMAKR_KEYDERIVER_PEACEMAKR_BOOTSTRAPPRIVATEKEYLOCATION=/keys/bootstrap
      - PEACEMAKR_KEYDERIVER_PEACEMAKR_HOST=peacemakr-services
    depends_on:
      - peacemakr-services
    links:
      - peacemakr-services
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
  redis:
    image: "redis:alpine"
  test:
    image: peacemakr-python-sdk-test
    environment:
      - PEACEMAKR_TEST_URL=http://peacemakr-services:80
    depends_on:
      - peacemakr-services
      - keyderiver-cloud
    links:
      - peacemakr-services
      - keyderiver-cloud
