# coding: utf-8

"""
    Peacemakr

    This API describes the Peacemakr services, which enable seamless application layer encryption and verification.  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301
import setuptools.command.build_py
import distutils.cmd
import distutils.log
import subprocess
import setuptools
import sys
import os
import shutil
import platform

NAME = "peacemakr-sdk"
VERSION = "0.0.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]

CORE_CRYPTO_URL_BASE="https://github.com/peacemakr-io/peacemakr-core-crypto/releases/download/"
CORE_CRYPTO_VERSION="v0.2.0/"

class InstallCoreCryptoCommand(distutils.cmd.Command):
  """A custom command to run Pylint on all Python source files."""

  description = 'run Pylint on Python source files'
  user_options = []
  def initialize_options(self):
    """Set default values for options."""
    pass

  def finalize_options(self):
    """Post-process options."""
    pass

  def _execute_command(self, command):
      subprocess.check_output(command, stderr=subprocess.STDOUT)

  def _is_pyversion_in_range(self, tuple, major_version, minor_version):
      return tuple[0] == major_version and tuple[1] == minor_version

  def _install_from_artifact(self, tar_filename, core_crypto_so_filename, core_crypto_shared_filename, core_crypto_cpp_shared_filename):
      site_package_dir = next(p for p in sys.path if 'site-packages' in p)
      get_command = "wget -q " + CORE_CRYPTO_URL_BASE + CORE_CRYPTO_VERSION + tar_filename
      unzip_command = "tar -zxvf " + tar_filename

      self._execute_command(get_command.split(" "))
      self._execute_command(unzip_command.split(" "))

        # copying file
      shutil.copyfile(core_crypto_so_filename, site_package_dir+"/"+core_crypto_so_filename)
      shutil.copyfile("lib/"+core_crypto_shared_filename, "/usr/local/lib/"+core_crypto_shared_filename)
      shutil.copyfile("lib/"+core_crypto_cpp_shared_filename, "/usr/local/lib/"+core_crypto_cpp_shared_filename)

  def _virtualenv_enabled(self):
      """Checks virtualenv is enabled or not"""
      return hasattr(sys, 'real_prefix')

  def _install_from_source(self):
      site_package_dir = "none"
      if self._virtualenv_enabled():
          site_package_dir = next(p for p in sys.path if 'site-packages' in p)
      git_clone_command = ["git" ,"clone", "https://github.com/peacemakr-io/peacemakr-core-crypto.git"]
      rm_clone_command = ["rm", "-rf", "peacemakr-core-crypto"]
      install_command = ["cd", "peacemakr-core-crypto/bin", "&&", "./release-python.sh", "local", site_package_dir, "release"]
      # clone the repo
      self.announce(
        'Cloning core-crypto @: %s' % ("https://github.com/peacemakr-io/peacemakr-core-crypto.git"),
        level=distutils.log.INFO)
      self._execute_command(git_clone_command)

      # check openssl and cmake

      # running release commands
      self.announce(
        'Installing core-crytpo into %s %s' % (str(site_package_dir), " ".join(install_command)),
        level=distutils.log.INFO)
      os.system(" ".join(install_command))

      # remove peacemakr-core-crypto
      self.announce(
        'Removing core-crytpo folder',
        level=distutils.log.INFO)
      self._execute_command(rm_clone_command)

  def run(self):
    """Run command.
    # TODO: Remind user to set LD_LIBRARY_PATH for Ubuntu in README
    """
    os_type = sys.platform
    machine_type = platform.machine()
    python_version = platform.python_version_tuple()
    tar_filename = ""
    core_crypto_so_filename = ""
    core_crypto_shared_filename = ""
    core_crypto_cpp_shared_filename = ""

    if os_type == "darwin":
        if machine_type == "x86_64" and self._is_pyversion_in_range(python_version, '3', '7'):
            # install from artifact
            tar_filename = "peacemakr-core-crypto-python-macos-x86_64.tar.gz"
            core_crypto_so_filename = "peacemakr_core_crypto_python.cpython-37m-darwin.so"
            core_crypto_shared_filename = "libpeacemakr-core-crypto.dylib"
            core_crypto_cpp_shared_filename = "libpeacemakr-core-crypto-cpp.dylib"

            self._install_from_artifact(tar_filename, core_crypto_so_filename, core_crypto_shared_filename, core_crypto_cpp_shared_filename)

        else:
            # install from src
            self.announce("Installing core-crypto from source", level=distutils.log.INFO)
            self._install_from_source()

    elif os_type == "linux":
        # TODO: detect Ubuntu or Debian only!
        import distro
        linux_distribution = distro.linux_distribution(full_distribution_name=False)[0]
        
        if linux_distribution in ["debian", "ubuntu"] and machine_type == "x86_64" and self._is_pyversion_in_range(python_version, '3', '7'):
            # install from artifact
            tar_filename = "peacemakr-core-crypto-python-ubuntu-x86_64.tar.gz"
            core_crypto_so_filename = "peacemakr_core_crypto_python.cpython-36m-x86_64-linux-gnu.so"
            core_crypto_shared_filename = "libpeacemakr-core-crypto.so"
            core_crypto_cpp_shared_filename = "libpeacemakr-core-crypto-cpp.so"

            self._install_from_artifact(tar_filename, core_crypto_so_filename, core_crypto_shared_filename, core_crypto_cpp_shared_filename)

        else:
            # install from src
            self.announce("Installing in Non-Debian Linux, installing core-crypto from source", level=distutils.log.INFO)
            self._install_from_source()
    else:
        sys.exit("Error: OS not supported. We only support Ubuntu and MacOS at the moment.")

    



class BuildPyCommand(setuptools.command.build_py.build_py):
  """Custom build command."""

  def run(self):
    self.run_command('install_core_crypto')
    setuptools.command.build_py.build_py.run(self)

setup(
    cmdclass={
        'install_core_crypto': InstallCoreCryptoCommand,
        'build_py': BuildPyCommand,
    },
    name=NAME,
    version=VERSION,
    description="Peacemakr",
    python_requires='>=3.6',
    author_email="",
    url="",
    keywords=["Peacemakr"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    This API describes the Peacemakr services, which enable seamless application layer encryption and verification.  # noqa: E501
    """
)
